---


- name: Make apache own htdocs directory
  file:
    state: directory
    path: "{{ m_htdocs }}"
    owner: "{{ user_apache }}"
    group: "{{ group_apache }}"
    mode: 0775

- name: Ensure mw-temp directory configured
  file:
    state: directory
    path: "{{ m_paths.mw_temp.path }}"
    owner: "{{ m_paths.mw_temp.owner }}"
    group: "{{ m_paths.mw_temp.group }}"
    mode: "{{ m_paths.mw_temp.mode }}"

- name: write the apache config file
  template:
    src: httpd.conf.j2
    dest: "{{ path_apache_conf }}"
  notify:
    - restart apache

- name: Ensure Apache environment variables set properly
  template:
    src: etc-sysconfig-httpd.j2
    dest: "{{ path_apache_startup_config }}"
  notify:
    - restart apache


- name: Ensure Apache modules installed (RedHat/CentOS only)
  yum:
    name:
      - mod_ssl
      - mod_proxy_html
    state: present



- name: Ensure Composer configured
  include_role:
    name: composer

# Now that PHP is installed, start apache
- name: ensure apache is running (and enable it at boot)
  service:
    name: "{{ service_apache }}"
    state: started
    enabled: yes
  when: docker_skip_tasks is not defined or not docker_skip_tasks



